ROX-14929 move test to gha
stackrox/workflow pull request #99
Opened 2023-02-22 18:41 UTC by davdhacs

2023-02-22 19:31 UTC, BradLugo requested changes

2023-02-22 19:31 UTC, BradLugo commented on .github/workflows/test.yml
> +        make test
Looks like the `test` target in the Makefile in the root directory does this, so you might be able to do something like `run: make test`

2023-02-22 20:02 UTC, BradLugo approved these changes

2023-02-22 20:02 UTC, BradLugo commented on .github/workflows/test.yml
> +on: push
I don't know enough about CircleCI to know what events triggered the workflow, but this LGTM

2023-02-22 20:07 UTC, merged

2023-02-23 08:37 UTC, Maddosaurus reviewed
LGTM, thanks for the migration!